import type { CustodyCase, CustodyStatus, DamageVerdict, EvidenceItem, EvidenceKind } from "@/lib/types";
export type ContractCase = { id?: string; title?: string; scope?: string; team?: string; challenger?: string; bond?: string; status?: string; target_date?: string; repository_url?: string; release_ref?: string; promise_terms?: string; outcome?: string; team_allocation?: string; challenger_allocation?: string; confidence?: number; reasoning?: string; };
export type ContractEvidence = { id?: string; promise_id?: string; kind?: string; url?: string; note?: string; submitted_by?: string; submitted_at?: string; };
const statuses: CustodyStatus[] = ["open", "evidence_submitted", "settled", "undetermined", "recovered_undetermined"];
const outcomes: DamageVerdict[] = ["fulfilled", "partially_fulfilled", "not_fulfilled", "undetermined"];
export function parseContractList<T>(value: unknown): T[] { if (Array.isArray(value)) return value as T[]; if (typeof value !== "string" || !value.trim()) return []; const parsed=JSON.parse(value); return Array.isArray(parsed) ? parsed as T[] : []; }
export function toCustodyCase(item: ContractCase, evidence: EvidenceItem[] = []): CustodyCase {
 const outcome=outcomes.includes(item.outcome as DamageVerdict) ? item.outcome as DamageVerdict : undefined;
 return { id:Number(item.id ?? 0), title:item.title ?? "Untitled promise", category:item.scope ?? "Release", lender:item.team ?? "", borrower:item.challenger ?? "", deposit:BigInt(item.bond ?? 0), status:statuses.includes(item.status as CustodyStatus) ? item.status as CustodyStatus : "open", startedAt:"", dueAt:item.target_date ?? "", repositoryUrl:item.repository_url ?? "", releaseRef:item.release_ref ?? "", promiseTerms:item.promise_terms ?? "", pickupEvidence:evidence.filter(x=>x.kind==="release_evidence").length, returnEvidence:evidence.filter(x=>x.kind==="counter_evidence").length, verdict: outcome ? { class:outcome, releaseToBorrower:BigInt(item.challenger_allocation ?? 0), releaseToLender:BigInt(item.team_allocation ?? 0), confidence:Number(item.confidence ?? 0), reasoning:item.reasoning ?? "" } : undefined };
}
export function toEvidenceItem(item: ContractEvidence): EvidenceItem { const kind:EvidenceKind=item.kind === "counter_evidence" ? "counter_evidence" : "release_evidence"; return {id:Number(item.id ?? 0), caseId:Number(item.promise_id ?? 0), kind, url:item.url ?? "", note:item.note ?? "", submittedBy:item.submitted_by ?? "", submittedAt:item.submitted_at ?? ""}; }
export function isWalletCase(item: CustodyCase, address?: string) { const value=address?.toLowerCase(); return Boolean(value && (item.lender.toLowerCase()===value || item.borrower.toLowerCase()===value)); }
