"use client";

import { use, useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { ArrowLeft, RefreshCcw, ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { StatusBadge } from "@/components/status-badge";
import { formatGen, shortAddress } from "@/lib/utils";
import { readCustodi, writeCustodi, formatGenLayerError, type WriteIdentity } from "@/lib/genlayer";
import { parseContractList, toCustodyCase, toEvidenceItem, type ContractCase, type ContractEvidence } from "@/lib/custodi-contract";
import { useWallet } from "@/lib/wallet";
import type { CustodyCase, EvidenceItem } from "@/lib/types";

export default function PromiseDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = use(params); const wallet = useWallet();
  const [promise, setPromise] = useState<CustodyCase | null>(null); const [evidence, setEvidence] = useState<EvidenceItem[]>([]); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { try { setError(""); const [raw, evidenceRaw] = await Promise.all([readCustodi("get_promise", [String(id)]), readCustodi("get_evidence", [String(id)])]); if (!raw) { setPromise(null); return; } const record = typeof raw === "string" ? JSON.parse(raw) as ContractCase : raw as ContractCase; const items = parseContractList<ContractEvidence>(evidenceRaw).map(toEvidenceItem); setEvidence(items); setPromise(toCustodyCase(record, items)); } catch (caught) { setError(formatGenLayerError(caught, "Could not load this promise.")); } }, [id]);
  useEffect(() => { void load(); }, [load]);
  async function write(method: string) { if (!wallet.address) return; setBusy(true); setError(""); try { const identity: WriteIdentity = wallet.mode === "browser" && wallet.privateKey ? { mode: "browser", privateKey: wallet.privateKey } : { mode: "injected", address: wallet.address }; await writeCustodi(identity, method, [String(id)]); await load(); } catch (caught) { setError(formatGenLayerError(caught)); } finally { setBusy(false); } }
  if (!promise) return <div className="space-y-4"><p>{error || "Loading promise…"}</p><Button variant="outline" onClick={() => void load()}>Retry</Button></div>;
  const mine = wallet.address?.toLowerCase(); const isTeam = mine === promise.lender.toLowerCase(); const isChallenger = mine === promise.borrower.toLowerCase();
  return <div className="space-y-6"><div className="flex items-start justify-between gap-4"><div><Link href="/cases" className="inline-flex items-center gap-1 text-sm underline"><ArrowLeft className="h-4 w-4"/>All promises</Link><p className="mt-4 font-mono text-xs uppercase tracking-[.2em] text-amberline">Promise #{promise.id}</p><h1 className="text-4xl font-black">{promise.title}</h1></div><div className="flex gap-2"><StatusBadge status={promise.status}/><Button variant="outline" size="sm" onClick={() => void load()}><RefreshCcw className="h-4 w-4"/></Button></div></div>
  <section className="grid gap-4 md:grid-cols-3"><Card><CardHeader><CardTitle>Bond</CardTitle></CardHeader><CardContent className="text-2xl font-black">{formatGen(promise.deposit)}</CardContent></Card><Card><CardHeader><CardTitle>Repository</CardTitle></CardHeader><CardContent><a className="break-all underline" href={promise.repositoryUrl} target="_blank" rel="noreferrer">{promise.repositoryUrl}</a></CardContent></Card><Card><CardHeader><CardTitle>Exact release</CardTitle></CardHeader><CardContent className="font-mono">{promise.releaseRef}</CardContent></Card></section>
  <section className="grid gap-6 lg:grid-cols-[1fr_380px]"><Card><CardHeader><CardTitle>Stored promise</CardTitle></CardHeader><CardContent className="space-y-4"><p className="font-semibold">{promise.category}</p><p className="whitespace-pre-wrap text-sm leading-6">{promise.promiseTerms}</p><p className="text-xs">Evidence closes: {promise.dueAt}</p><h3 className="font-bold">Bound evidence</h3>{evidence.length ? <ul className="space-y-3">{evidence.map(item => <li key={item.id} className="rounded border p-3"><p className="font-semibold capitalize">{item.kind.replace("_", " ")}</p><a className="break-all underline" href={item.url} target="_blank" rel="noreferrer">{item.url}</a><p className="text-xs">{item.note}</p></li>)}</ul> : <p className="text-sm">No evidence submitted yet.</p>}</CardContent></Card>
  <div className="space-y-4"><Card><CardHeader><CardTitle>Participants</CardTitle></CardHeader><CardContent className="space-y-3 text-sm"><p><b>Team:</b> {shortAddress(promise.lender)}</p><p><b>Designated challenger:</b> {shortAddress(promise.borrower)}</p><p className="text-xs">Fulfilled: 100% team. Partial: 70% team / 30% challenger. Not fulfilled: 100% challenger. Undetermined: team recovers its bond.</p></CardContent></Card>{promise.verdict ? <Card><CardHeader><CardTitle>Consensus outcome</CardTitle></CardHeader><CardContent className="space-y-2"><p className="font-bold capitalize">{promise.verdict.class.replace("_", " ")}</p><p className="text-sm">{promise.verdict.reasoning}</p><p className="text-xs">Team: {formatGen(promise.verdict.releaseToLender)} · Challenger: {formatGen(promise.verdict.releaseToBorrower)}</p></CardContent></Card> : null}<div className="flex flex-wrap gap-2"><Link href={`/evidence?case=${promise.id}`}><Button variant="secondary">Submit evidence</Button></Link>{(isTeam || isChallenger) && (promise.status === "open" || promise.status === "evidence_submitted") ? <Button disabled={busy || promise.pickupEvidence === 0} onClick={() => void write("challenge_promise")}><ShieldCheck className="h-4 w-4"/>Review fulfillment</Button> : null}{(isTeam || isChallenger) && promise.status === "undetermined" ? <Button variant="outline" disabled={busy} onClick={() => void write("recover_undetermined")}>Recover undetermined bond</Button> : null}{isTeam && promise.status === "open" ? <Button variant="outline" disabled={busy} onClick={() => void write("recover_expired_without_evidence")}>Recover expired empty promise</Button> : null}</div>{error ? <p className="rounded border border-red-500 p-3 text-sm text-red-500">{error}</p> : null}</div></section></div>;
}
